name: Publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - run: yarn

      - run: yarn test

      - run: yarn build

      - name: Version
        run: yarn version "${GITHUB_REF:11}" -i

      - name: Publish
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Storybook
        run: yarn deploy-storybook
